// WARNING: DO NOT EDIT.  This file is automatically generated
// Written by aws-amplify-serverless-plugin/1.4.1 on 2019-04-19T13:43:42.187Z

const awsmobile = {
    aws_cloud_logic_custom: [
        {
            endpoint: 'https://wfdr5f2odi.execute-api.eu-west-1.amazonaws.com/dev',
            name: 'ApiGatewayRestApi',
            region: 'eu-west-1'
        }
    ],
    aws_cognito_region: 'eu-west-1',
    aws_project_region: 'eu-west-1',
    aws_user_pools_id: 'eu-west-1_XqihhHKdE',
    aws_user_pools_web_client_id: '6lga2qb45hheelt313r313tfp1'
};

export default awsmobile;
